theme: jekyll-theme-chirpy

lang: ko-KR
timezone: Asia/Seoul

title: KdHyeok Dev Blog
tagline: 포트폴리오 & 알고리즘 & 개발 기록
description: 개발자 포트폴리오, 알고리즘 풀이, 일상 기록
url: "https://kdHyeok.github.io"
baseurl: ""

github:
  username: kdHyeok

social:
  name: kdHyeok
  email: ""
  links:
    - https://github.com/kdHyeok

avatar: "/assets/img/avatar.webp"

toc: true

comments:
  provider:

paginate: 10

assets:
  self_host:
    enabled: false

pwa:
  enabled: false

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      toc: true
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

exclude:
  - Gemfile
  - Gemfile.lock
  - "*.gem"
  - README.md
  - run.py
  - update_projects.py
  - create_algo_post.py
  - find_todos.py
